---
abstract: 'Format validation for Net:: related strings'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: Validate::Net
name: Validate-Net
no_index:
  directory:
    - inc
    - t
requires:
  Class::Default: 0.02
  Test::More: 0.42
  perl: 5.005
version: 0.6
