# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Validate-Net
version:      0.5
version_from: lib/Validate/Net.pm
installdirs:  site
requires:
    Class::Default:                0.2
    File::Spec:                    0.83
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
